import { useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { api } from '../../api/client';

const VEHICLE_TYPES = [
  { value: 'van',       label: 'Cargo Van / Sprinter' },
  { value: 'box_truck', label: 'Box Truck / Cube Van' },
  { value: 'semi',      label: 'Semi Trailer / 18-Wheeler' },
  { value: 'pickup',    label: 'Pickup Truck / SUV' },
  { value: 'bus',       label: 'Bus / Shuttle' },
  { value: 'other',     label: 'Other' },
];

const COVERAGE_TYPES = [
  { value: 'full',    label: 'Full Wrap' },
  { value: 'partial', label: 'Partial Wrap' },
  { value: 'spot',    label: 'Spot Graphics' },
];

function fmtDollar(n: number) {
  if (n >= 1000) return `$${(n / 1000).toFixed(1)}K`.replace('.0K', 'K');
  return `$${n.toLocaleString()}`;
}

export default function QuickQuoteModal({ onClose }: { onClose: () => void }) {
  const [vehicleType, setVehicleType] = useState('van');
  const [vehicleCount, setVehicleCount] = useState(1);
  const [coverage, setCoverage] = useState('full');
  const [copied, setCopied] = useState(false);

  const { data, isFetching } = useQuery({
    queryKey: ['quick-quote', vehicleType, vehicleCount, coverage],
    queryFn: () => api.quickQuote(vehicleType, vehicleCount, coverage),
    staleTime: 60_000,
    enabled: vehicleCount >= 1,
  });

  function handleCopy() {
    if (!data) return;
    const text = `Quick estimate for ${vehicleCount} ${vehicleType.replace('_', ' ')}(s) — ${coverage} wrap:\n$${data.low.toLocaleString()} – $${data.high.toLocaleString()} (${fmtDollar(data.perVehicle)}/vehicle)\n\nGenerated by WrapOS`;
    navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  }

  return (
    <>
      <div style={{ position: 'fixed', inset: 0, background: 'rgba(0,0,0,.65)', zIndex: 3000 }} onClick={onClose} />
      <div style={{
        position: 'fixed', top: '50%', left: '50%', transform: 'translate(-50%,-50%)',
        width: 420, background: 'var(--bg-elev)', border: '1px solid var(--border)',
        borderRadius: 16, padding: 24, zIndex: 3001,
        boxShadow: '0 24px 80px rgba(0,0,0,.7)',
      }}
        onMouseDown={(e) => e.stopPropagation()}
      >
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 20 }}>
          <div>
            <div style={{ fontSize: 15, fontWeight: 700, color: 'var(--text)' }}>⚡ Quick Quote</div>
            <div style={{ fontSize: 11, color: 'var(--text-muted)', marginTop: 2 }}>Ballpark estimate for a prospect call</div>
          </div>
          <button onClick={onClose} style={{ background: 'none', border: 'none', cursor: 'pointer', color: 'var(--text-muted)', fontSize: 18 }}>✕</button>
        </div>

        {/* Inputs */}
        <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 10, marginBottom: 12 }}>
          <div>
            <label style={{ fontSize: 10, fontWeight: 700, textTransform: 'uppercase', letterSpacing: '0.08em', color: 'var(--text-faint)', display: 'block', marginBottom: 4 }}>
              Vehicle Type
            </label>
            <select
              className="input"
              value={vehicleType}
              onChange={(e) => setVehicleType(e.target.value)}
              style={{ width: '100%', fontSize: 12 }}
            >
              {VEHICLE_TYPES.map(t => (
                <option key={t.value} value={t.value}>{t.label}</option>
              ))}
            </select>
          </div>
          <div>
            <label style={{ fontSize: 10, fontWeight: 700, textTransform: 'uppercase', letterSpacing: '0.08em', color: 'var(--text-faint)', display: 'block', marginBottom: 4 }}>
              # of Vehicles
            </label>
            <input
              type="number"
              className="input"
              min={1} max={500}
              value={vehicleCount}
              onChange={(e) => setVehicleCount(Math.max(1, parseInt(e.target.value) || 1))}
              style={{ width: '100%', fontSize: 12 }}
            />
          </div>
        </div>

        <div style={{ marginBottom: 16 }}>
          <label style={{ fontSize: 10, fontWeight: 700, textTransform: 'uppercase', letterSpacing: '0.08em', color: 'var(--text-faint)', display: 'block', marginBottom: 6 }}>
            Coverage
          </label>
          <div style={{ display: 'flex', gap: 6 }}>
            {COVERAGE_TYPES.map(c => (
              <button
                key={c.value}
                onClick={() => setCoverage(c.value)}
                style={{
                  flex: 1, padding: '7px 4px', borderRadius: 8, fontSize: 11, fontWeight: 600, cursor: 'pointer',
                  border: coverage === c.value ? '1px solid var(--accent)' : '1px solid var(--border)',
                  background: coverage === c.value ? 'rgba(244,85,28,0.12)' : 'var(--surface)',
                  color: coverage === c.value ? 'var(--accent)' : 'var(--text-muted)',
                }}
              >
                {c.label}
              </button>
            ))}
          </div>
        </div>

        {/* Result */}
        <div style={{
          background: 'var(--surface)', border: '1px solid var(--border)', borderRadius: 12,
          padding: '18px 20px', marginBottom: 14, minHeight: 90,
          display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center',
        }}>
          {isFetching ? (
            <div style={{ color: 'var(--text-muted)', fontSize: 13 }}>Calculating…</div>
          ) : data ? (
            <>
              <div style={{ fontSize: 28, fontWeight: 900, color: 'var(--text)', letterSpacing: '-1px', marginBottom: 4 }}>
                {fmtDollar(data.low)} – {fmtDollar(data.high)}
              </div>
              <div style={{ fontSize: 12, color: 'var(--text-muted)' }}>
                {fmtDollar(data.perVehicle)}/vehicle · Recommended: <strong style={{ color: 'var(--accent)' }}>{fmtDollar(data.recommended)}</strong>
              </div>
              {data.vehicleCount >= 5 && (
                <div style={{ fontSize: 10, color: 'var(--text-faint)', marginTop: 4 }}>
                  Includes fleet discount
                </div>
              )}
              <div style={{ fontSize: 9, color: 'var(--text-faint)', marginTop: 6 }}>
                {data.fromHistory ? `Based on your ${data.historyJobs} similar jobs` : 'Industry average estimate'}
              </div>
            </>
          ) : (
            <div style={{ color: 'var(--text-faint)', fontSize: 13 }}>Enter vehicle details above</div>
          )}
        </div>

        <div style={{ display: 'flex', gap: 8 }}>
          <button
            onClick={handleCopy}
            disabled={!data}
            style={{
              flex: 1, padding: '10px', borderRadius: 8, fontSize: 12, fontWeight: 700, cursor: 'pointer',
              border: '1px solid var(--accent)', background: copied ? 'rgba(0,217,126,0.1)' : 'rgba(244,85,28,0.1)',
              color: copied ? '#00d97e' : 'var(--accent)',
            }}
          >
            {copied ? '✓ Copied' : 'Copy to Clipboard'}
          </button>
          <button
            onClick={onClose}
            style={{
              padding: '10px 16px', borderRadius: 8, fontSize: 12, cursor: 'pointer',
              border: '1px solid var(--border)', background: 'var(--surface)', color: 'var(--text-muted)',
            }}
          >
            Close
          </button>
        </div>
      </div>
    </>
  );
}
