import { useState, useMemo } from 'react';

interface Props {
  onClose: () => void;
  companyName?: string;
}

const VEHICLE_PRESETS = [
  { label: 'Cargo Van', sqft: 225, costLow: 3500, costHigh: 5500 },
  { label: 'Box Truck (16ft)', sqft: 335, costLow: 5500, costHigh: 8500 },
  { label: 'Box Truck (24ft)', sqft: 450, costLow: 7000, costHigh: 11000 },
  { label: 'Semi + Trailer', sqft: 700, costLow: 12000, costHigh: 25000 },
  { label: 'Pickup Truck', sqft: 175, costLow: 2800, costHigh: 4500 },
  { label: 'Full-Size SUV', sqft: 185, costLow: 3000, costHigh: 4800 },
];

const IMPRESSIONS_PER_VEHICLE = 50_000;
const LIFESPAN_YEARS = 5;

function fmt(n: number) {
  if (n >= 1_000_000) return `$${(n / 1_000_000).toFixed(2)}M`;
  if (n >= 1_000) return `$${Math.round(n / 1_000)}K`;
  return `$${Math.round(n)}`;
}

function fmtNum(n: number) {
  if (n >= 1_000_000) return `${(n / 1_000_000).toFixed(1)}M`;
  if (n >= 1_000) return `${Math.round(n / 1_000)}K`;
  return String(Math.round(n));
}

export default function ROICalculatorModal({ onClose, companyName }: Props) {
  const [vehicleType, setVehicleType] = useState(0);
  const [fleetSize, setFleetSize] = useState(5);
  const [dailyMiles, setDailyMiles] = useState(100);

  const preset = VEHICLE_PRESETS[vehicleType];

  const roi = useMemo(() => {
    const totalCostLow = preset.costLow * fleetSize;
    const totalCostHigh = preset.costHigh * fleetSize;
    const dailyImpressions = IMPRESSIONS_PER_VEHICLE * fleetSize;
    const annualImpressions = dailyImpressions * 365;
    const lifetimeImpressions = annualImpressions * LIFESPAN_YEARS;
    const cpmLow = (totalCostHigh / (lifetimeImpressions / 1000));
    const cpmHigh = (totalCostLow / (lifetimeImpressions / 1000));
    const billboardCpm = 5.5;
    const billboardEquivalentCost = (lifetimeImpressions / 1000) * billboardCpm;
    const savingsVsBillboard = billboardEquivalentCost - totalCostHigh;
    return {
      totalCostLow, totalCostHigh,
      dailyImpressions, annualImpressions, lifetimeImpressions,
      cpmLow, cpmHigh,
      billboardEquivalentCost, savingsVsBillboard,
    };
  }, [vehicleType, fleetSize, dailyMiles, preset]);

  function copyToClipboard() {
    const text = `Wrap ROI Report — ${companyName || 'Your Fleet'}
Fleet: ${fleetSize} × ${preset.label}
Investment: ${fmt(roi.totalCostLow)}–${fmt(roi.totalCostHigh)}
Daily impressions: ${fmtNum(roi.dailyImpressions)}/day
Annual impressions: ${fmtNum(roi.annualImpressions)}/year
5-year total: ${fmtNum(roi.lifetimeImpressions)} impressions
CPM: $${roi.cpmLow.toFixed(2)}–$${roi.cpmHigh.toFixed(2)} (vs. billboard ~$5.50)
Savings vs. billboard: ${fmt(roi.savingsVsBillboard)}+

Generated by WrapLeads${companyName ? ` — ${companyName}` : ''}`;
    navigator.clipboard.writeText(text);
  }

  return (
    <div className="modal-backdrop" onClick={onClose}>
      <div className="modal-box roi-calc-box" onClick={(e) => e.stopPropagation()}>
        <div className="modal-header">
          <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" style={{ color: 'var(--accent)' }}><line x1="18" y1="20" x2="18" y2="10"/><line x1="12" y1="20" x2="12" y2="4"/><line x1="6" y1="20" x2="6" y2="14"/></svg>
          <h2 className="modal-title" style={{ margin: 0 }}>Wrap ROI Calculator</h2>
          <button className="modal-close" onClick={onClose}>✕</button>
        </div>

        <div className="roi-calc-inputs">
          <div className="field-group">
            <label className="field-label">Vehicle Type</label>
            <select className="select" value={vehicleType} onChange={(e) => setVehicleType(Number(e.target.value))}>
              {VEHICLE_PRESETS.map((v, i) => (
                <option key={i} value={i}>{v.label}</option>
              ))}
            </select>
          </div>
          <div className="field-group">
            <label className="field-label">Fleet Size</label>
            <div style={{ display: 'flex', alignItems: 'center', gap: 10 }}>
              <input
                type="range" min={1} max={200} value={fleetSize}
                onChange={(e) => setFleetSize(Number(e.target.value))}
                style={{ flex: 1 }}
              />
              <span style={{ fontSize: 20, fontWeight: 700, minWidth: 40, textAlign: 'right' }}>{fleetSize}</span>
            </div>
          </div>
          <div className="field-group">
            <label className="field-label">Avg Miles/Day per Vehicle</label>
            <div style={{ display: 'flex', alignItems: 'center', gap: 10 }}>
              <input
                type="range" min={20} max={500} step={10} value={dailyMiles}
                onChange={(e) => setDailyMiles(Number(e.target.value))}
                style={{ flex: 1 }}
              />
              <span style={{ fontSize: 16, fontWeight: 600, minWidth: 50, textAlign: 'right' }}>{dailyMiles}mi</span>
            </div>
          </div>
        </div>

        <div className="roi-results-grid">
          <div className="roi-result-card roi-result-investment">
            <div className="roi-result-label">Wrap Investment</div>
            <div className="roi-result-value">{fmt(roi.totalCostLow)}–{fmt(roi.totalCostHigh)}</div>
            <div className="roi-result-sub">one-time, {LIFESPAN_YEARS}-year lifespan</div>
          </div>
          <div className="roi-result-card roi-result-impressions">
            <div className="roi-result-label">Daily Impressions</div>
            <div className="roi-result-value">{fmtNum(roi.dailyImpressions)}</div>
            <div className="roi-result-sub">{fmtNum(roi.annualImpressions)}/year</div>
          </div>
          <div className="roi-result-card roi-result-lifetime">
            <div className="roi-result-label">5-Year Total Impressions</div>
            <div className="roi-result-value">{fmtNum(roi.lifetimeImpressions)}</div>
            <div className="roi-result-sub">for {fleetSize} {fleetSize === 1 ? 'vehicle' : 'vehicles'}</div>
          </div>
          <div className="roi-result-card roi-result-cpm">
            <div className="roi-result-label">Cost Per 1,000 Impressions</div>
            <div className="roi-result-value">${roi.cpmLow.toFixed(2)}–${roi.cpmHigh.toFixed(2)}</div>
            <div className="roi-result-sub">vs. billboard ~$5.50 CPM</div>
          </div>
          <div className="roi-result-card roi-result-savings" style={{ gridColumn: '1 / -1' }}>
            <div className="roi-result-label">Savings vs. Equivalent Billboard Coverage</div>
            <div className="roi-result-value" style={{ color: 'var(--green)' }}>
              {roi.savingsVsBillboard > 0 ? `${fmt(roi.savingsVsBillboard)}+ saved` : 'More cost-effective than billboard'}
            </div>
            <div className="roi-result-sub">
              Billboard equivalent: {fmt(roi.billboardEquivalentCost)} · Wrap cost: {fmt(roi.totalCostHigh)}
            </div>
          </div>
        </div>

        <div style={{ display: 'flex', gap: 8, marginTop: 16 }}>
          <button className="btn btn-primary" style={{ flex: 1 }} onClick={copyToClipboard}>
            Copy ROI Report
          </button>
          <button className="btn" onClick={onClose}>Close</button>
        </div>
      </div>
    </div>
  );
}
