import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';

const API = 'http://localhost:3001';

export default defineConfig({
  plugins: [react()],
  build: { outDir: '../dist', emptyOutDir: true },
  server: {
    port: 5173,
    proxy: {
      '/auth':          API,
      '/leads':         API,
      '/carriers':      API,
      '/searches':      API,
      '/settings':      API,
      '/analytics':     API,
      '/apollo':        API,
      '/stripe':        API,
      '/ai':            API,
      '/bids':          API,
      '/calls':         API,
      '/blueprint':     API,
      '/content':       API,
      '/devices':       API,
      '/email-queue':   API,
      '/integrations':  API,
      '/jobs':          API,
      '/me':            API,
      '/mission':       API,
      '/notifications': API,
      '/portal-links':  API,
      '/portal':        API,
      '/portfolio':     API,
      '/proposals':     API,
      '/quotes':        API,
      '/quote-request': API,
      '/track':         API,
      '/vision':        API,
      '/webhooks':      API,
      '/health':        API,
      '/activity':      API,
      '/onboarding':    API,
      '/admin':         API,
      '/demo':          API,
      '/migrate':       API,
      '/for':           API,
      '/compare':       API,
      '/calculator':    API,
      '/stats.json':    API,
      '/opportunities':      API,
      '/wrap-my-fleet':     API,
      '/inbound-leads':     API,
      '/case-studies':      API,
      '/milestones':        API,
      '/tasks':             API,
      '/tools':             API,
      '/review':            API,
      '/subcontractors':    API,
      '/twilio':            API,
      '/fleet':             API,
    },
  },
});
